/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package monitor;

import graficos.Alocacao;
import graficos.Cpu;
import graficos.CpuTodos;
import graficos.Disco;
import graficos.DiscoTodos;
import graficos.Elasticidade;
import graficos.ElasticidadeFisica;
import graficos.ElasticidadeMicroeconomia;
import graficos.Media;
import graficos.Memoria;
import graficos.MemoriaTodos;
import graficos.Rede;
import graficos.RedeTodos;
import graficos.TensaoStress;
import graficos.TomCat;
import graficos.TomCatBarra;
import graficos.TomCatBarraTodos;
import graficos.TomCatTodos;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import javax.swing.JPanel;
import monitor.ArquivoForm.MyCustomFilter;
import paineis.NewClass;
import paineis.NewClass1;
import util.LeitorLog;

/**
 *
 * @author leleco
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {

        initComponents();
        painel1.setSize(100, 200);
        painel2.setSize(100, 200);
        painel3.setSize(100, 200);
        painel4.setSize(100, 200);
        painel1.setPreferredSize(new Dimension(100, 100));
        painel2.setPreferredSize(new Dimension(100, 100));
        painel3.setPreferredSize(new Dimension(100, 100));
        painel4.setPreferredSize(new Dimension(100, 100));
//        jButton1.setVisible(false);
//        jComboBox1.setVisible(false);
//        jLabel5.setVisible(false);
//        jLabel6.setVisible(false);
//        jTextField1.setVisible(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cpu1 = new graficos.Cpu();
        jSplitPane1 = new javax.swing.JSplitPane();
        painelEsquerdo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbP1 = new javax.swing.JComboBox();
        mvCPU = new javax.swing.JTextField();
        cbP2 = new javax.swing.JComboBox();
        mvMemoria = new javax.swing.JTextField();
        cbP3 = new javax.swing.JComboBox();
        mvDisco = new javax.swing.JTextField();
        cbP4 = new javax.swing.JComboBox();
        mvRede = new javax.swing.JTextField();
        cbP5 = new javax.swing.JComboBox();
        mvPainel5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        pnTodos = new javax.swing.JTextField();
        painelAbrir = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        painel5 = new javax.swing.JPanel();
        painelMenu = new javax.swing.JPanel();
        painel1 = new javax.swing.JPanel();
        painel2 = new javax.swing.JPanel();
        painel3 = new javax.swing.JPanel();
        painel4 = new javax.swing.JPanel();
        painelEscondido = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setDividerLocation(600);

        painelEsquerdo.setBackground(new java.awt.Color(232, 196, 161));
        painelEsquerdo.setMaximumSize(new java.awt.Dimension(327, 131068));
        painelEsquerdo.setMinimumSize(new java.awt.Dimension(300, 151));
        painelEsquerdo.setLayout(new javax.swing.BoxLayout(painelEsquerdo, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(6, 0));

        jLabel1.setText(" Gráficos");
        jPanel1.add(jLabel1);

        jLabel2.setText(" Máquina Virtual");
        jPanel1.add(jLabel2);

        cbP1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CPU", "Memória", "Disco", "Rede", "Média", "Alocação", "Tempo de Resposta - TomCat", "Barra", "TensaoStress", "Elasticidade Fisica", "Elasticidade Microeconomia", "Elasticidade" }));
        cbP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbP1ActionPerformed(evt);
            }
        });
        jPanel1.add(cbP1);

        mvCPU.setText("1");
        mvCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvCPUActionPerformed(evt);
            }
        });
        jPanel1.add(mvCPU);

        cbP2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CPU", "Memória", "Disco", "Rede", "Média", "Alocação", "Tempo de Resposta - TomCat", "Barra", "TensãoStress", "Elasticidade Fisica", "Elasticidade Microeconomia", "Elasticidade" }));
        cbP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbP2ActionPerformed(evt);
            }
        });
        jPanel1.add(cbP2);

        mvMemoria.setText("1");
        mvMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(mvMemoria);

        cbP3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CPU", "Memória", "Disco", "Rede", "Média", "Alocação", "Tempo de Resposta - TomCat", "Barra", "TensãoStress", "Elasticidade Fisica", "Elasticidade Microeconomia", "Elasticidade" }));
        cbP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbP3ActionPerformed(evt);
            }
        });
        jPanel1.add(cbP3);

        mvDisco.setText("1");
        mvDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvDiscoActionPerformed(evt);
            }
        });
        jPanel1.add(mvDisco);

        cbP4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CPU", "Memória", "Disco", "Rede", "Média", "Alocação", "Tempo de Resposta - TomCat", "Barra", "TensãoStress", "Elasticidade Fisica", "Elasticidade Microeconomia", "Elasticidade" }));
        cbP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbP4ActionPerformed(evt);
            }
        });
        jPanel1.add(cbP4);

        mvRede.setText("1");
        mvRede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvRedeActionPerformed(evt);
            }
        });
        jPanel1.add(mvRede);

        cbP5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CPU", "Memória", "Disco", "Rede", "Média", "Alocação", "Tempo de Resposta - TomCat", "Barra", "TensãoStress", "Elasticidade Fisica", "Elasticidade Microeconomia", "Elasticidade" }));
        cbP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbP5ActionPerformed(evt);
            }
        });
        jPanel1.add(cbP5);

        mvPainel5.setText("1");
        jPanel1.add(mvPainel5);

        painelEsquerdo.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMinimumSize(new java.awt.Dimension(134, 20));
        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        jLabel3.setText(" Gráficos");
        jPanel2.add(jLabel3);

        jLabel4.setText(" Painel");
        jPanel2.add(jLabel4);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CPU", "Memória", "Disco", "Rede", "Tempo de Resposta - TomCat", "Barra" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox5);

        pnTodos.setText("5");
        pnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnTodosActionPerformed(evt);
            }
        });
        jPanel2.add(pnTodos);

        painelEsquerdo.add(jPanel2);

        painelAbrir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelAbrir.setLayout(new java.awt.GridLayout(1, 2));

        jButton3.setText("Abrir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        painelAbrir.add(jButton3);

        painelEsquerdo.add(painelAbrir);

        painel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painel5.setDoubleBuffered(false);
        painel5.setEnabled(false);
        painel5.setLayout(new java.awt.BorderLayout());
        painelEsquerdo.add(painel5);

        jSplitPane1.setRightComponent(painelEsquerdo);

        painelMenu.setBackground(new java.awt.Color(255, 255, 255));
        painelMenu.setLayout(new java.awt.GridLayout(4, 0));

        painel1.setBackground(new java.awt.Color(255, 255, 255));
        painel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painel1.setDoubleBuffered(false);
        painel1.setEnabled(false);
        painel1.setPreferredSize(new java.awt.Dimension(500, 150));
        painel1.setLayout(new java.awt.GridLayout(1, 0));
        painelMenu.add(painel1);

        painel2.setBackground(new java.awt.Color(255, 255, 255));
        painel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painel2.setDoubleBuffered(false);
        painel2.setEnabled(false);
        painel2.setPreferredSize(new java.awt.Dimension(500, 150));
        painel2.setLayout(new java.awt.GridLayout(1, 0));
        painelMenu.add(painel2);

        painel3.setBackground(new java.awt.Color(255, 255, 255));
        painel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painel3.setDoubleBuffered(false);
        painel3.setEnabled(false);
        painel3.setPreferredSize(new java.awt.Dimension(500, 150));
        painel3.setLayout(new java.awt.GridLayout(1, 0));
        painelMenu.add(painel3);

        painel4.setBackground(new java.awt.Color(255, 255, 255));
        painel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painel4.setDoubleBuffered(false);
        painel4.setEnabled(false);
        painel4.setPreferredSize(new java.awt.Dimension(500, 150));
        painel4.setLayout(new java.awt.GridLayout(1, 0));
        painelMenu.add(painel4);

        jSplitPane1.setLeftComponent(painelMenu);

        getContentPane().add(jSplitPane1);

        painelEscondido.setLayout(null);

        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\Users\\leleco\\Dropbox\\ProjetosNetBeans\\Monitor\\src\\arquivosTexto"));
        jFileChooser1.setDialogTitle("Abrir Arquivos de Log");
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        painelEscondido.add(jFileChooser1);
        jFileChooser1.setBounds(-83, 5, 614, 397);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setMinimumSize(new java.awt.Dimension(914, 27));
        jPanel3.setPreferredSize(new java.awt.Dimension(134, 27));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jLabel5.setText("Diretório");
        jPanel3.add(jLabel5);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "C:\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-12-09-2013-a\\\\", "C:\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-12-09-2013-b\\\\", "C:\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-12-09-2013-c\\\\", "C:\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-12-09-2013-d\\\\", "C:\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-12-09-2013-e\\\\", " ", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-12-09-2013-e\\\\", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-12-09-2013-d\\\\", " ", "C:\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-12-09-2013-e\\\\", "C:\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-12-09-2013-d\\\\", " ", "C:\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-09-10-2013-benc\\\\", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-09-10-2013-benc\\\\", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-09-10-2013-tudo\\\\", " ", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-19-10-2013\\\\", " ", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-21-10-2013-blast\\\\", " ", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-06-11-2013\\\\", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-06-11-2013-2\\\\", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-06-11-2013-3\\\\", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-06-11-2013-4\\\\", "C:\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-06-11-2013-4\\\\", " ", " ", "C:\\\\Users\\\\emanuel\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-09-10-2013-benc\\\\", "C:\\\\Users\\\\emanuel\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-12-09-2013-d\\\\", "C:\\\\Users\\\\emanuel\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-12-09-2013-e\\\\", "C:\\\\Users\\\\emanuel\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-09-10-2013-tudo\\\\", " ", "----", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-11-01-2014\\\\", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-10-06-2014-2mv-azure\\\\", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-11-06-2014-4MVS\\\\", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-15-06-2014-1ON3MA\\\\", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-15-06-2014-1ON3MA-2\\\\", "----micro e blast ajustados", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-06-11-2013-4-ajustado\\\\", "C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-21-10-2013-blast-ajustado\\\\", "----", " ", " " }));
            jComboBox1.setPreferredSize(new java.awt.Dimension(65, 20));
            jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox1ActionPerformed(evt);
                }
            });
            jPanel3.add(jComboBox1);

            painelEscondido.add(jPanel3);
            jPanel3.setBounds(0, 0, 134, 27);

            jPanel4.setLayout(new java.awt.GridLayout(2, 2));

            jTextField1.setText("C:\\\\Users\\\\leleco\\\\Dropbox\\\\ProjetosNetBeans\\\\Monitor\\\\src\\\\arquivosTexto\\\\log-11-06-2014-4MVS\\\\");
                jTextField1.setAutoscrolls(false);
                jTextField1.setMaximumSize(new java.awt.Dimension(200, 2147483647));
                jTextField1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextField1ActionPerformed(evt);
                    }
                });
                jPanel4.add(jTextField1);

                jButton1.setText("Ok");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                    }
                });
                jPanel4.add(jButton1);

                jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
                jLabel6.setText("jLabel6");
                jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                jPanel4.add(jLabel6);

                jButton2.setText("Abrir");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton2ActionPerformed(evt);
                    }
                });
                jPanel4.add(jButton2);

                painelEscondido.add(jPanel4);
                jPanel4.setBounds(0, 0, 986, 46);

                getContentPane().add(painelEscondido);

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void pnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnTodosActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        exibeGraficoTodos(jComboBox5.getSelectedIndex(), selecionaPainel(pnTodos.getText()));
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void cbP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbP1ActionPerformed
        exibeGrafico(cbP1.getSelectedIndex(), painel1, Integer.parseInt(mvCPU.getText()));
    }//GEN-LAST:event_cbP1ActionPerformed

    private void cbP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbP2ActionPerformed
        exibeGrafico(cbP2.getSelectedIndex(), painel2, Integer.parseInt(mvMemoria.getText()));
    }//GEN-LAST:event_cbP2ActionPerformed

    private void cbP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbP3ActionPerformed
        exibeGrafico(cbP3.getSelectedIndex(), painel3, Integer.parseInt(mvDisco.getText()));
    }//GEN-LAST:event_cbP3ActionPerformed

    private void cbP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbP4ActionPerformed
        exibeGrafico(cbP4.getSelectedIndex(), painel4, Integer.parseInt(mvRede.getText()));
    }//GEN-LAST:event_cbP4ActionPerformed

    
    
    
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try {
            LeitorLog.atualizaDiretorios(jComboBox1.getSelectedItem().toString());
            jLabel6.setText(jComboBox1.getSelectedItem().toString());
            jTextField1.setText(jComboBox1.getSelectedItem().toString());
        } catch (Exception e) {
            LeitorLog.atualizaDiretorios(LeitorLog.diretorioBase);
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void cbP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbP5ActionPerformed
      exibeGrafico(cbP5.getSelectedIndex(), painel5, Integer.parseInt(mvPainel5.getText()));
    }//GEN-LAST:event_cbP5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try {
                LeitorLog.atualizaDiretorios(jTextField1.getText());
                    } catch (Exception e) {
            LeitorLog.atualizaDiretorios(LeitorLog.diretorioBase);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mvCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mvCPUActionPerformed

    private void mvMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mvMemoriaActionPerformed

    private void mvDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvDiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mvDiscoActionPerformed

    private void mvRedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvRedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mvRedeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jFileChooser1.setDialogTitle("Selecione o diretório de log a ser aberto");
        jFileChooser1.setFileSelectionMode(jFileChooser1.DIRECTORIES_ONLY);
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == jFileChooser1.APPROVE_OPTION) {
            File arquivo = jFileChooser1.getSelectedFile();
            String s = arquivo.getAbsolutePath();
            s = s.replace("\\", "\\\\") + "\\";
            jLabel6.setText(s);
            jTextField1.setText(s);
//            String s = jFileChooser1.getSelectedFile().getName();
//            s = s.replace( '\'', '\\' );
//            jLabel6.setText(s);
            try {
                LeitorLog.atualizaDiretorios(jTextField1.getText());
            } catch (Exception e) {
                LeitorLog.atualizaDiretorios(LeitorLog.diretorioBase);
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        jFileChooser1.setDialogTitle("Selecione o diretório de log a ser aberto");
        jFileChooser1.setFileSelectionMode(jFileChooser1.DIRECTORIES_ONLY);
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == jFileChooser1.APPROVE_OPTION) {
            File arquivo = jFileChooser1.getSelectedFile();
            String s = arquivo.getAbsolutePath();
            s = s.replace("\\", "\\\\") + "\\";
            jLabel6.setText(s);
            jTextField1.setText(s);
//            String s = jFileChooser1.getSelectedFile().getName();
//            s = s.replace( '\'', '\\' );
//            jLabel6.setText(s);
            try {
                LeitorLog.atualizaDiretorios(jTextField1.getText());
            } catch (Exception e) {
                LeitorLog.atualizaDiretorios(LeitorLog.diretorioBase);
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void exibeGrafico(int painel, JPanel p, int mv) {
        try {
            switch (painel) {
                case 0:
                    Cpu cpu = new Cpu(mv);
                    cpu.criaGrafico(p);
                    setVisible(true);
                    break;
                case 1:
                    Memoria m = new Memoria(mv);
                    m.criaGrafico(p);
                    setVisible(true);
                    break;
                case 2:
                    Disco disco = new Disco(mv);
                    disco.criaGrafico(p);
                    setVisible(true);
                    break;
                case 3:
                    Rede rede = new Rede(mv);
                    rede.criaGrafico(p);
                    setVisible(true);
                    break;
                case 4:
                    Media media = new Media();
                    media.criaGrafico(p);
                    setVisible(true);
                    break;
                case 5:
                    Alocacao alocacao = new Alocacao();
                    alocacao.criaGrafico(p);
                    setVisible(true);
                    break;
                case 6:
                    TomCat t = new TomCat(mv);
                    t.criaGrafico(p);
                    setVisible(true);
                    break;
                case 7:
                    TomCatBarra tb = new TomCatBarra(mv);
                    tb.criaGrafico(p);
                    setVisible(true);
                    break;
                case 8:
                    TensaoStress tensaoStress = new TensaoStress();
                    tensaoStress.criaGrafico(p);
                    setVisible(true);
                    break;
                case 9:
                    ElasticidadeFisica elasticidadeFisica = new ElasticidadeFisica();
                    elasticidadeFisica.criaGrafico(p);
                    setVisible(true);
                    break;
                case 10:
                    ElasticidadeMicroeconomia elasticidadeMicroeconomia = new ElasticidadeMicroeconomia();
                    elasticidadeMicroeconomia.criaGrafico(p);
                    setVisible(true);
                    break;
                case 11:
                    Elasticidade elasticidade = new Elasticidade();
                    elasticidade.criaGrafico(p);
                    setVisible(true);
                    break;
                
            } // switch
        } catch (IOException e) {
            System.out.println("iiiiiiiiiiiiiiiiiiiiiiiiie");
        }
    }

    private void exibeGraficoTodos(int painel, JPanel p) {
        try {
            switch (painel) {
                case 0:
                    CpuTodos cpuT = new CpuTodos();
                    cpuT.criaGrafico(p);
                    setVisible(true);
                    break;
                case 1:
                    MemoriaTodos memT = new MemoriaTodos();
                    memT.criaGrafico(p);
                    setVisible(true);
                    break;
                case 2:
                    DiscoTodos discoT = new DiscoTodos();
                    discoT.criaGrafico(p);
                    setVisible(true);
                    break;
                case 3:
                    RedeTodos redeT = new RedeTodos();
                    redeT.criaGrafico(p);
                    setVisible(true);
                    break;
                case 4:
                    TomCatTodos t = new TomCatTodos();
                    t.criaGrafico(p);
                    setVisible(true);
                    break;
                case 5:
                    TomCatBarraTodos tt = new TomCatBarraTodos();
                    tt.criaGrafico(p);
                    setVisible(true);
                    break;
                case 6:
                    break;
            } // switch
        } catch (IOException e) {
        }
    }

    private JPanel selecionaPainel(String k) {
        int i = Integer.parseInt(k);
        JPanel j = null;
        switch (i) {
            case 1:
                j = painel1;
                break;
            case 2:
                j = painel2;
                break;
            case 3:
                j = painel3;
                break;
            case 4:
                j = painel4;
                break;
            case 5:
                j = painel5;
                break;
            default:
                j = painel5;
        }
        return j;
    }

    class MyCustomFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory();// || file.getAbsolutePath().endsWith(".txt");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Text documents (*.txt)";
        }
    } 
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //  setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbP1;
    private javax.swing.JComboBox cbP2;
    private javax.swing.JComboBox cbP3;
    private javax.swing.JComboBox cbP4;
    private javax.swing.JComboBox cbP5;
    private graficos.Cpu cpu1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField mvCPU;
    private javax.swing.JTextField mvDisco;
    private javax.swing.JTextField mvMemoria;
    private javax.swing.JTextField mvPainel5;
    private javax.swing.JTextField mvRede;
    private javax.swing.JPanel painel1;
    private javax.swing.JPanel painel2;
    private javax.swing.JPanel painel3;
    private javax.swing.JPanel painel4;
    private javax.swing.JPanel painel5;
    private javax.swing.JPanel painelAbrir;
    private javax.swing.JPanel painelEscondido;
    private javax.swing.JPanel painelEsquerdo;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JTextField pnTodos;
    // End of variables declaration//GEN-END:variables
}
